version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - run:
          name: Run code
          command:
            python main.py

workflows:
  version: 2
  build:
    jobs:
      - build
