version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            
      - run:
          name: Create test-reports directory
          command: mkdir -p test-reports

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python test.py

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

workflows:
  build:
    jobs:
      - build
