version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install pytest

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            mkdir test-results
            pytest --junitxml=test-results/junit.xml test.py

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-reports

workflows:
  build:
    jobs:
      - build
